=== JovanDjordjevic/materijali_sa_fakulteta/materijali sa osnovnih studija/4. godina/Projektovanje baza podataka/vezbe/cas_11/xquery_momir/primer5.xsd
<?xml version="1.0"?>

<!-- Def: Kazemo da je xml datoteka *dobro formirana* ako postuje pravila xml standarda -->
<!-- https://www.w3.org/XML/ -->

<!-- Stukturu xml datoteka mozemo da definisemo preko xsd sheme ili dtd pravila -->
<!-- Def: Kazemo da je xml datoteka *validna* ako postuje pravila definisana preko xsd/dtd -->

<!-- Zakljucak -->
<!-- 1: Ako xml datoteka nije dobro formirana, onda nije prava xml datoteka -->
<!-- 2: Ako je xml datoteka validna, onda je i dobro formirana -->
<!-- 3: Ako je xml datoteka dobro formirana, to ne znaci da je validna -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="list">
  <xs:complexType>
    <xs:sequence minOccurs="0" maxOccurs="unbounded">
      <xs:element name="person">
        <xs:complexType>
          <xs:all>
            <xs:element name="fname" type="xs:string"/>
            <xs:element name="lname" type="xs:string"/>
          </xs:all>
          <xs:attribute name="person_id" type="xs:int"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

</xs:schema>

=== JovanDjordjevic/materijali_sa_fakulteta/materijali sa osnovnih studija/4. godina/Projektovanje baza podataka/vezbe/cas_11/xquery_momir/person_refactored.xml
<?xml version="1.0" encoding="utf-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="primer5.xsd">
  <person person_id="1">
    <fname>Kapek</fname>
    <lname>Sainnouine</lname>
  </person>
  <person person_id="2">
    <fname>Sajon</fname>
    <lname>Rondela</lname>
  </person>
  <person person_id="3">
    <fname>Likame</fname>
    <lname>Örrtmons</lname>
  </person>
  <person person_id="4">
    <fname>Slar</fname>
    <lname>Manlanth</lname>
  </person>
  <person person_id="5">
    <fname>Stoma</fname>
    <lname>Milu</lname>
  </person>
  <person person_id="6">
    <fname>Nirtam</fname>
    <lname>Sklöd</lname>
  </person>
  <person person_id="7">
    <fname>Sungam</fname>
    <lname>Dulbåd</lname>
  </person>
  <person person_id="8">
    <fname>Sraref</fname>
    <lname>Encmelt</lname>
  </person>
</list>
